apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-henvendelse-db
  namespace: teamnks
  labels:
    team: teamnks
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://sf-henvendelse-db.ekstern.dev.nav.no"
    - "https://sf-henvendelse-db.intern.dev.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-f1-micro
        diskAutoresize: true
        autoBackupHour: 6
        databases:
          - name: sf-henvendelse-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
  env:
    - name: VIEW_PAGE_SIZE
      value: "50"
