apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-henvendelse-db
  namespace: teamnks
  labels:
    team: teamnks
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 3
    max: 6
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://sf-henvendelse-db.nav.no"
    - "https://sf-henvendelse-db.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-4-16384
        diskAutoresize: true
        autoBackupHour: 6
        maintenance:
          day: 1
          hour: 3
        databases:
          - name: sf-henvendelse-prod
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
  env:
    - name: VIEW_PAGE_SIZE
      value: "50"
    - name: CONTEXT
      value: "PROD"
